### ISSUE TITLE
Create React components

### ISSUE THREAD

**Issue by brentocracy** [brentocracy/kindly#11]
# Set up component directories with `index.js` files

* Create list of all needed components first
* Create skeleton rendering of layout/style
* Pseudo-code list of conditional renders and hooks/effects with each component

**Comment by DaveToth77** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create React components ( Issue #11)](https://trello.com/c/WqvGxVaz/40-create-react-components-issue-11)
