### ISSUE TITLE
Set up Redux store

### ISSUE THREAD

**Issue by brentocracy** [brentocracy/kindly#12]
[https://github.com/bradtraversy/proshop_mern/tree/master/frontend/src](url)

For a good Redux setup, we want:

`/constants` to hold the exports of action type strings
-- Each component will have a script exporting respective action types

`actions` to import the constant action types and set up the dispatch type and result for each action
-- Again, each component gets a file

`reducers` to import the action types and set up the reducer switch statements to determine how state gets changed
-- Each component gets a file

**Comment by DaveToth77** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set up Redux store (Issue #12)](https://trello.com/c/ibqATaZM/41-set-up-redux-store-issue-12)

**Comment by DaveToth77** [comment]
Redux not used in current iteration of App
