### ISSUE TITLE
Feature- Add cancel event/good deed functionality

### ISSUE THREAD

**Issue by DaveToth77** [brentocracy/kindly#25]
- add cancel event buttons on good deed and event cards
- incorporate cancelEvent/GoodDeed functionality onClick to remove event/good deed from DB

**Comment by brentocracy** [comment]
See above issue -- this button should render and activate when the user is a host of an event/deed.

If the user is not a host, they can JOIN or LEAVE an event, which will toggle based on whether or not the user is an attendee.

Both checks should be in functions which are called in the component render.
