### ISSUE TITLE
Feature- Add join event/good deed

### ISSUE THREAD

**Issue by DaveToth77** [brentocracy/kindly#26]
- add join buttons to event/good deed cards
- Event- onclick add event to user and add user to attendees
- Good Deed- onClick add Good deed to user and add user to helper, remove join button

**Comment by brentocracy** [comment]
I think the button to JOIN should be toggled to LEAVE. 

We can run a check to see if the user is an attendee or not.

If the user is a host, there should be a special CANCEL button instead of the JOIN/LEAVE toggle.
