### ISSUE TITLE
Feature - Profile page

### ISSUE THREAD

**Issue by DaveToth77** [brentocracy/kindly#32]
- populate profile page with user data ( First/Last name, location, kindly points, upcoming events/good deeds, connections)
- Add "Connect with me" button when viewing other users profiles that will add them to you connections. ( This is probably fine for the MVP, but it should be approved by the profile owner in the future)
-

**Comment by brentocracy** [comment]
UPDATED: 

-- `Connections` are no longer part of the initial app functionality.

This issue has therefore been completed.
