### ISSUE TITLE
Functionality to filter through either registered events/deeds or homepage to check user's host or attendee status

### ISSUE THREAD

**Issue by michellewehr** [brentocracy/kindly#35]

**Comment by brentocracy** [comment]
I'm not sure what you mean in the title -- can you elaborate?

It seems like you're saying we need a distinction between events the user hosts and events the user attends on the sidebar view of Upcoming Events. Is that correct?

This would mean running a function that checks if the `user._id` is equal to either the `hostId` or any of the `attendee.id` in the array of `attendees.` Then, we can conditionally render something in front of a hosted event, ie "**YOU'RE HOSTING THIS EVENT**.

**Comment by brentocracy** [comment]
@michellewehr let me know if this issue still persists and what it means. :)
